In [36]:
file = open('test_schedule (1).inc', 'r', encoding='utf8')
lines = file.readlines()

import re
import pandas as pd

test=[]
for line in lines:
    for i in re.findall(r'\d\*',line):
        line= line[:line.index(i)] + 'default '*int(i[:-1])  + line[line.index(i)+len(i):]
    line = re.sub(r'\-- .*','',line)
#     line = re.sub(r' +\\n|\\n', '', line)
    line = re.sub(r'\n',' ', line)
    line = re.sub(r'/+ +','/',line)
    line = re.sub('\\t', '',line)
    line = re.sub('  +', ' ',line)
    test.append(line) if line.isspace() == False else True

words = ['COMPDAT ', 'DATES ', 'COMPDATL '] 

data_df = pd.DataFrame(columns=['Date','Well name','Local grid name','I','J','K upper','K lower','Flag on connection',
                                'Saturation table','Transmissibility factor','Well bore diameter','Effective Kh','Skin factor',
                                'D-factor','Dir_well_penetrates_grid_block','Press_eq_radius'])

# test

In [40]:
block=[]
# date = float('Nan')
date = ''
well_name = ''

name = [' ']
row_index =0
while row_index < len(test):
    if test[row_index] == 'END ' : break
    
    if (test[row_index][-1] != '/') & (test[row_index] not in words):
        while test[row_index] != '/':
            row_index+=1
        
    if test[row_index] in words:
        name.append(test[row_index])
#         print('name',name[-2])
        print(block)
        data_df, date = func(data_df, block, name[-2],date)
        
        block = []
        row_index +=1
    if (test[row_index] == '/') : 
        row_index +=1
        continue
    block.append(test[row_index])
    row_index+=1
    
data_df, date = func(data_df, block, name[-2],date)
block

[]
["'W1' 10 10 1 3 OPEN default 1 2 1 default default default 1.0 /", "'W2' 32 10 1 3 OPEN default 1 2 1 default default default 2.0 /"]
["'W3' 5 36 2 2 OPEN default 1 2 1 default default default 3.0 /", "'W4' 40 30 1 3 OPEN default 1 2 1 default default default 4.0 /"]
["'W5' 21 21 4 4 OPEN default 1 2 1 default default default 5.0 /"]
['01 JUN 2018 /']
['01 JUL 2018 /']
["'W3' 32 10 1 1 OPEN default 1 2 1 default default default 1.0718 /", "'W5' 21 21 1 3 OPEN default 1 2 1 default default default 5.0 /"]
['01 AUG 2018 /', '01 SEP 2018 /']
["'W1' 10 10 2 3 OPEN default 1 2 1 default default default 1.0918 /", "'W2' 32 10 1 2 OPEN default 1 2 1 default default default 2.0 /"]
["'W3' 'LGR1' 10 10 2 2 OPEN default 1 2 1 default default default 1.0918 /"]
['01 OCT 2018 /']
['01 NOV 2018 /']

['01 DEC 2018 /']

In [38]:
def func(df, x, word, date):
    if x == []: return df, date
    if word == 'COMPDAT ':
        for i in range(len(x)):
            values = re.findall(r'\w+',x[i])
            df = df.append({
                'Date': date,
                'Well name' : '',
                'Local grid name' : values[0],
                'I':values[1],
                'J':values[2],
                'K upper':values[3],
                'K lower':values[4],
                'Flag on connection':values[5],
                'Saturation table':values[6],
                'Transmissibility factor':values[7],
                'Well bore diameter':values[8],
                'Effective Kh':values[9],
                'Skin factor':values[10],
                'D-factor':values[11],
                'Dir_well_penetrates_grid_block':values[12],
                'Press_eq_radius':values[13]+'.'+values[14]
            }, ignore_index=True)
    elif word == 'DATES ':
        for i in range(len(x)):
            date = re.sub('\/','', x[i])
            df = df.append({
                'Date': date,
                'Well name' :'',
                'Local grid name' :'',
                'I':'',
                'J':'',
                'K upper':'',
                'K lower':'',
                'Flag on connection':'',
                'Saturation table':'',
                'Transmissibility factor':'',
                'Well bore diameter':'',
                'Effective Kh':'',
                'Skin factor':'',
                'D-factor':'',
                'Dir_well_penetrates_grid_block':'',
                'Press_eq_radius':''
            }, ignore_index=True)
    else:
        for i in range(len(x)):
            values =  re.findall(r'\w+',x[i]) 
            df = df.append({
                'Date': date,
                'Well name' :values[1],
                'Local grid name' : values[0],
                'I':values[2],
                'J':values[3],
                'K upper':values[4],
                'K lower':values[5],
                'Flag on connection':values[6],
                'Saturation table':values[7],
                'Transmissibility factor':values[8],
                'Well bore diameter':values[9],
                'Effective Kh':values[10],
                'Skin factor':values[11],
                'D-factor':values[12],
                'Dir_well_penetrates_grid_block':values[13],
                'Press_eq_radius':values[14]+'.'+values[15]
            }, ignore_index=True)
        
    return df, date

In [39]:
data_df

,Date,Well name,Local grid name,I,J,K upper,K lower,Flag on connection,Saturation table,Transmissibility factor,Well bore diameter,Effective Kh,Skin factor,D-factor,Dir_well_penetrates_grid_block,Press_eq_radius
0,,,W1,10,10,1,3,OPEN,default,1,2,1,default,default,default,1.0
1,,,W2,32,10,1,3,OPEN,default,1,2,1,default,default,default,2.0
2,,,W3,5,36,2,2,OPEN,default,1,2,1,default,default,default,3.0
3,,,W4,40,30,1,3,OPEN,default,1,2,1,default,default,default,4.0
4,,,W5,21,21,4,4,OPEN,default,1,2,1,default,default,default,5.0
5,01 JUN 2018,,,,,,,,,,,,,,,
6,01 JUL 2018,,,,,,,,,,,,,,,
7,01 JUL 2018,,W3,32,10,1,1,OPEN,default,1,2,1,default,default,default,1.0718
8,01 JUL 2018,,W5,21,21,1,3,OPEN,default,1,2,1,default,default,default,5.0
9,01 AUG 2018,,,,,,,,,,,,,,,
10,01 SEP 2018,,,,,,,,,,,,,,,
11,01 SEP 2018,,W1,10,10,2,3,OPEN,default,1,2,1,default,default,default,1.0918
12,01 SEP 2018,,W2,32,10,1,2,OPEN,default,1,2,1,default,default,default,2.0
13,01 SEP 2018,LGR1,W3,10,10,2,2,OPEN,default,1,2,1,default,default,default,1.0918
14,01 OCT 2018,,,,,,,,,,,,,,,
15,01 NOV 2018,,,,,,,,,,,,,,,
16,01 DEC 2018,,,,,,,,,,,,,,,

6